### ISSUE TITLE
Mysql.md有个错误

### ISSUE THREAD

**Issue by xianyunyh** [disxo/PHP-interview-myway#7]
[https://github.com/disxo/PHP-interview-myway/blob/master/mysql.md](mysql)
- 

TimeStamp | 4 | 以YYYY-MM-DD的格式显示，比如：2009-07-19
-- | -- | --

VarChar(M) | M | 变长字符串，要求M<=255
-- | -- | --

- Timestamp 的长度 应该是 6，格式应该为 `1970-01-01 00:00:01.000000`
- varchar 中M的大小，其实不限制255 varchar(1000)也是ok的， 最大是65535

**Comment by disxo** [comment]
好的，我有空改下，谢谢指出
